# This workflow will use Maven to build a package and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Build and test

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
          settings-path: ${{ github.workspace }} # location for the settings.xml file

      - name: Install libxkbcommon-x11
        run: sudo apt-get update && sudo apt-get install -y libxkbcommon-x11-0

      - name: Clean and Build with Maven
        uses: GabrielBB/xvfb-action@v1
        with:
          run: mvn -B clean package --file pom.xml

      - name: Publish to GitHub Packages Apache Maven
        uses: GabrielBB/xvfb-action@v1
        with:
          run: mvn deploy -s settings.xml
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
